# Generated by Django 4.0.6 on 2022-10-15 06:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='media/images/')),
                ('clientname', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default=None, max_length=50, null=True)),
                ('phone', models.CharField(max_length=40)),
                ('message', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=20)),
                ('petage', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogname', models.CharField(default=None, max_length=50, null=True)),
                ('description', models.CharField(default=None, max_length=300, null=True)),
                ('author', models.CharField(default=None, max_length=300, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='media/images/')),
                ('date', models.DateField(default=None, null=True)),
                ('editor', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(default=None, null=True, to='home.tag', verbose_name='My Tags')),
            ],
        ),
    ]
