# Generated by Django 2.2.12 on 2022-06-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogtitle',
            new_name='blogname',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
