# Generated by Django 4.0.5 on 2022-06-28 11:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_clientsfeedback_alter_blog_id_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsfeedback',
            name='editor',
        ),
        migrations.AddField(
            model_name='blog',
            name='editor',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
