# Generated by Django 4.0.5 on 2022-06-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_clientsfeedback_editor_blog_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
